export default { 
    SHOP_OWNER: 'SHOP_OWNER',
    AGENT: 'AGENT',
    SHOP_USER: 'SHOP_USER',
    SHOP_MANAGER: 'SHOP_MANAGER',
    EDITOR: 'EDITOR',
    FRANCHISER: 'FRANCHISER',
    TECHNICIAN: 'TECHNICIAN',
};